version: '3.3'
services:
  database:
    image: postgres:16.0-alpine3.18
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart:
      always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

